#!/bin/bash
# Setup PipeWire virtual I/O devices for Apollo Solo USB
# Creates individual named sources/sinks from the 10ch/6ch pro-audio streams.
#
# Apollo Solo USB channel map:
#   CAPTURE (10ch AUX0-9): AUX0=Mic1, AUX1=Mic2, AUX2-9=Virtual 1-8
#   PLAYBACK (6ch AUX0-5): AUX0=Mon L, AUX1=Mon R, AUX2=HP L, AUX3=HP R, AUX4-5=?
#
# Run after PipeWire is started and DSP is initialized:
#   bash configs/pipewire/setup-apollo-solo-usb.sh

set -euo pipefail

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pipewire/pipewire.conf.d"
CONF_FILE="$CONF_DIR/apollo-solo-usb-io.conf"

log() { echo "[apollo-solo-usb] $*"; }

# Wait for PipeWire
i=0
while ! pw-cli info 0 &>/dev/null; do
    sleep 1; i=$((i+1)); [ $i -ge 10 ] && { log "PipeWire not ready"; exit 1; }
done

# Find Apollo USB device
DEVICE_ID=$(pw-dump 2>/dev/null | python3 -c "
import json, sys
for obj in json.load(sys.stdin):
    props = obj.get('info', {}).get('props', {})
    if 'Apollo Solo USB' in props.get('alsa.card_name', '') and obj.get('type') == 'PipeWire:Interface:Device':
        print(obj['id']); break
" 2>/dev/null || true)

[ -z "$DEVICE_ID" ] && { log "Apollo Solo USB not found in PipeWire"; exit 1; }
log "Device ID: $DEVICE_ID"

# Set the pro-audio profile — gives the real 10ch capture / 6ch playback
# with proper AUX0-9 channel naming. (An earlier version of this script
# avoided pro-audio for a suspected "capture start bug" and fell back to
# a 3-channel analog-surround-2.1 profile instead — that fallback doesn't
# carry mic signal at all on this device and was never actually needed;
# pro-audio works. Looked up by name, not a hardcoded index: ACP assigns
# pro-audio a different index per device depending on how many surround
# permutation profiles it also generates.)
PROFILE_INDEX=$(pw-dump 2>/dev/null | python3 -c "
import json, sys
for obj in json.load(sys.stdin):
    if obj.get('id') != $DEVICE_ID: continue
    for p in obj.get('info', {}).get('params', {}).get('EnumProfile', []):
        if p.get('name') == 'pro-audio':
            print(p['index']); break
" 2>/dev/null || true)

[ -z "$PROFILE_INDEX" ] && { log "pro-audio profile not found on device $DEVICE_ID"; exit 1; }

wpctl set-profile "$DEVICE_ID" "$PROFILE_INDEX" 2>/dev/null || true
sleep 1
log "pro-audio profile set (index $PROFILE_INDEX)"

# Discover node names
eval "$(pw-dump 2>/dev/null | python3 -c "
import json, sys
for obj in json.load(sys.stdin):
    props = obj.get('info', {}).get('props', {})
    if 'Apollo Solo USB' not in props.get('alsa.card_name', ''): continue
    name = props.get('node.name', '')
    if 'input' in name and 'loopback' not in name: print(f'INPUT_NODE=\"{name}\"')
    if 'output' in name and 'loopback' not in name: print(f'OUTPUT_NODE=\"{name}\"')
" 2>/dev/null || echo 'INPUT_NODE="" ; OUTPUT_NODE=""')"

[ -z "$INPUT_NODE" ] && { log "Input node not found"; exit 1; }
[ -z "$OUTPUT_NODE" ] && { log "Output node not found"; exit 1; }
log "Input:  $INPUT_NODE"
log "Output: $OUTPUT_NODE"

# Generate loopback config
mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" << CONF
# Apollo Solo USB virtual I/O — auto-generated by setup-apollo-solo-usb.sh
# Input: $INPUT_NODE (10ch AUX0-9)
# Output: $OUTPUT_NODE (6ch AUX0-5)

context.modules = [

    # ═══════ CAPTURE SOURCES (Apollo → PipeWire) ═══════
    # pro-audio capture channels are named AUX0-AUX9: AUX0=Mic1, AUX1=Mic2

    # Mic/Instrument 1 (mono)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 1"
            capture.props = {
                audio.position    = [ AUX0 ]
                stream.dont-remix = true
                node.target       = "$INPUT_NODE"
                node.passive      = true
            }
            playback.props = {
                node.name   = "apollo_mic_1"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }

    # Mic/Instrument 2 (mono)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 2"
            capture.props = {
                audio.position    = [ AUX1 ]
                stream.dont-remix = true
                node.target       = "$INPUT_NODE"
                node.passive      = true
            }
            playback.props = {
                node.name   = "apollo_mic_2"
                media.class = "Audio/Source"
                audio.position = [ MONO ]
            }
        }
    }

    # Mic 1+2 Stereo
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 1+2"
            capture.props = {
                audio.position    = [ AUX0 AUX1 ]
                stream.dont-remix = true
                node.target       = "$INPUT_NODE"
                node.passive      = true
            }
            playback.props = {
                node.name   = "apollo_mic_stereo"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
            }
        }
    }

    # ═══════ PLAYBACK SINKS (PipeWire → Apollo) ═══════
    # pro-audio playback channels are named AUX0-AUX5: AUX0=Mon L, AUX1=Mon R

    # Monitor L/R (main speakers)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Monitor"
            capture.props = {
                node.name   = "apollo_monitor"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.target       = "$OUTPUT_NODE"
                audio.position    = [ AUX0 AUX1 ]
                stream.dont-remix = true
            }
        }
    }
]
CONF

log "Config written: $CONF_FILE"

# Restart PipeWire to load the loopback config
systemctl --user restart pipewire wireplumber 2>/dev/null || true
sleep 3

# Verify
NODES=$(wpctl status 2>/dev/null | grep -c 'Apollo' || echo 0)
log "Apollo nodes in wpctl: $NODES"
wpctl status 2>/dev/null | grep 'Apollo'
log "Done!"
